### ISSUE TITLE
Project Plan Endorsement changes

### ISSUE THREAD

**Issue by ben3000** [dbca-wa/science-projects-client#12]
Changes required for the Create New Project page:

- [x] Remove the Data Collection Required and Data Manager’s Endorsement items.
- [x] Remove the Plant Specimen Collection checkbox.
- [x] Rename “Biometrician Required?” to “Biometrician Endorsement Required?”
- [x] Spell out “HC Endorsement Required?” in full
- [x] Spell out “AEC Endorsement Required?” in full
- [x] Remove the “Interaction with Vertebrate Animals” checkbox.
- [x] Does the “Save” button do what the “Seek Endorsements” button does? If so, can we remove the “Seek Endorsements” button?
- [x] Create a pdf upload component and render when aec endorsement required
- [x] Endorsement auto approved when pdf file uploaded by superuser or aec
- [x] Save modal, interface and api call accept and send file where provided
- [x] Update database model to handle and provide these files 
- [x] Update frontend to display the file & name to indicate the pdf has been provided, and enable viewing of it
