### ISSUE TITLE
Add Images to RTE for Methodology (Project Plan)

### ISSUE THREAD

**Issue by idabblewith** [dbca-wa/science-projects-client#160]
NOTE: Rory has said that this functionality does not necessarily need to be in the RTE (the text section for methodology).
Instead, we will introduce a new optional section to the Project Plan for a methodology image that will be drag and drop/click to upload like other image sections.

- [x] Update model/serializers of Project Plan to accept image (create the model on medias app and reference project plan)
- [x] Update migrator SQL to account for the new field that is not present on original data
- [x] Create the component on the frontend and add it to the Project Plan tab
- [x] Create the types
- [x] Create the api call on the frontend to talk to the view for updating project plan
- [x] Create a separate view (if necessary) on the backend for handling adding this new image data
- [x] Update the Django template to optionally render the image if one exists, otherwise to ignore
