### ISSUE TITLE
Adjust Order and wording of Project Plan Items

### ISSUE THREAD

**Issue by idabblewith** [dbca-wa/science-projects-client#161]
- [ ] Aims
- [ ] Expected Outcomes (note plural)
- [ ] Knowledge Transfer
- [ ] Tasks and Milestones
- [ ] References
- [ ] Methodology
- [ ] Number of Voucher Specimens
- [ ] Data Management
- [ ] Related Science Projects
- [ ] Consolidated Funds (note change from Operating Budget)
- [ ] External Funds (note change from External Budget)
- [ ] Endorsements
